magick convert add-circle-outline.png         add-circle-outline.gif
magick convert analytics-outline.png          analytics-outline.gif
magick convert bar-chart-outline.png          bar-chart-outline.gif
magick convert bookmark-outline.png           bookmark-outline.gif
magick convert checkmark-circle-outline.png   checkmark-circle-outline.gif
magick convert cloud-download-outline.png     cloud-download-outline.gif
magick convert eye-outline.png                eye-outline.gif
magick convert file-tray-full-outline.png     file-tray-full-outline.gif
magick convert filter-outline.png             filter-outline.gif
magick convert game-controller-outline.png    game-controller-outline.gif
magick convert globe-outline.png              globe-outline.gif
magick convert icon.ico                       icon.ico
magick convert information-outline.png        information-outline.gif
magick convert link-outline.png               link-outline.gif
magick convert none.png                       none.gif
magick convert pie-chart-outline.png          pie-chart-outline.gif
magick convert refresh-outline.png            refresh-outline.gif
magick convert regex-outline.png              regex-outline.gif
magick convert remove-circle-outline.png      remove-circle-outline.gif
magick convert save-outline.png               save-outline.gif
magick convert search-outline.png             search-outline.gif
magick convert trash-outline.png              trash-outline.gif
magick convert settings-outline.png           settings-outline.gif