magick convert add-circle-outline.png         -resize x30 add-circle-outline.png
magick convert analytics-outline.png          -resize x30 analytics-outline.png
magick convert bar-chart-outline.png          -resize x30 bar-chart-outline.png
magick convert bookmark-outline.png           -resize x30 bookmark-outline.png
magick convert checkmark-circle-outline.png   -resize x30 checkmark-circle-outline.png
magick convert cloud-download-outline.png     -resize x30 cloud-download-outline.png
magick convert eye-outline.png                -resize x30 eye-outline.png
magick convert file-tray-full-outline.png     -resize x30 file-tray-full-outline.png
magick convert filter-outline.png             -resize x30 filter-outline.png
magick convert game-controller-outline.png    -resize x30 game-controller-outline.png
magick convert globe-outline.png              -resize x30 globe-outline.png
magick convert icon.ico                       -resize x30 icon.ico
magick convert information-outline.png        -resize x30 information-outline.png
magick convert link-outline.png               -resize x30 link-outline.png
magick convert none.png                       -resize x30 none.png
magick convert pie-chart-outline.png          -resize x30 pie-chart-outline.png
magick convert refresh-outline.png            -resize x30 refresh-outline.png
magick convert regex-outline.png              -resize x30 regex-outline.png
magick convert remove-circle-outline.png      -resize x30 remove-circle-outline.png
magick convert save-outline.png               -resize x30 save-outline.png
magick convert search-outline.png             -resize x30 search-outline.png
magick convert trash-outline.png              -resize x30 trash-outline.png
magick convert settings-outline.png           -resize x30 settings-outline.png