import lib.Var as VAR
from tkinter import ttk

def initStyles():
    STYLE_FRAME_DEFAULT = ttk.Style()
    STYLE_FRAME_DEFAULT.configure("TFrame", background=VAR.GUI_COLOR_PRIMARY)

    STYLE_FRAME_PRIMARY = ttk.Style()
    STYLE_FRAME_PRIMARY.configure(VAR.FRAME_STYLE_PRIMARY, background=VAR.GUI_COLOR_PRIMARY)

    STYLE_FRAME_SECONDARY = ttk.Style()
    STYLE_FRAME_SECONDARY.configure(VAR.FRAME_STYLE_SECONDARY, background=VAR.GUI_COLOR_SECONDARY)


    STYLE_LABEL_DEFAULT = ttk.Style()
    STYLE_LABEL_DEFAULT.configure("TLabel", background=VAR.GUI_COLOR_PRIMARY)

    STYLE_LABEL_PRIMARY = ttk.Style()
    STYLE_LABEL_PRIMARY.configure(VAR.LABEL_STYLE_PRIMARY, background=VAR.GUI_COLOR_PRIMARY)

    STYLE_LABEL_SECONDARY = ttk.Style()
    STYLE_LABEL_SECONDARY.configure(VAR.LABEL_STYLE_SECONDARY, background=VAR.GUI_COLOR_SECONDARY)

    STYLE_LABEL_WARNING = ttk.Style()
    STYLE_LABEL_WARNING.configure(VAR.LABEL_STYLE_WARNING, background=VAR.GUI_COLOR_WARNING)

    STYLE_LABEL_WARN_TEXT_PRIMARY = ttk.Style()
    STYLE_LABEL_WARN_TEXT_PRIMARY.configure(VAR.LABEL_STYLE_WARN_TEXT_PRIMARY, foreground=VAR.LABEL_COLOR_WARN_TEXT, background=VAR.GUI_COLOR_PRIMARY)

    STYLE_LABEL_WARN_TEXT_SECONDARY = ttk.Style()
    STYLE_LABEL_WARN_TEXT_SECONDARY.configure(VAR.LABEL_STYLE_WARN_TEXT_SECONDARY, foreground=VAR.LABEL_COLOR_WARN_TEXT, background=VAR.GUI_COLOR_SECONDARY)

    STYLE_LABEL_LINK_PRIMARY = ttk.Style()
    STYLE_LABEL_LINK_PRIMARY.configure(VAR.LABEL_STYLE_LINK_PRIMARY, foreground="blue", background=VAR.GUI_COLOR_PRIMARY)

    STYLE_LABEL_LINK_SECONDARY = ttk.Style()
    STYLE_LABEL_LINK_SECONDARY.configure(VAR.LABEL_STYLE_LINK_SECONDARY, foreground="blue", background=VAR.GUI_COLOR_SECONDARY)


    STYLE_BUTTON_DEFAULT = ttk.Style()
    STYLE_BUTTON_DEFAULT.configure("TButton", background=VAR.BUTTON_COLOR_PRIMARY, relief="groove")

    STYLE_BUTTON_PRIMARY = ttk.Style()
    STYLE_BUTTON_PRIMARY.configure(VAR.BUTTON_STYLE_PRIMARY, background=VAR.BUTTON_COLOR_PRIMARY)

    STYLE_BUTTON_TOGGLE = ttk.Style()
    STYLE_BUTTON_TOGGLE.configure(VAR.BUTTON_STYLE_TOGGLE, background=VAR.BUTTON_COLOR_TOGGLE)

    STYLE_BUTTON_CONFIRM = ttk.Style()
    STYLE_BUTTON_CONFIRM.configure(VAR.BUTTON_STYLE_CONFIRM, background=VAR.BUTTON_COLOR_CONFIRM)

    STYLE_BUTTON_CANCEL = ttk.Style()
    STYLE_BUTTON_CANCEL.configure(VAR.BUTTON_STYLE_CANCEL, background=VAR.BUTTON_COLOR_CANCEL)


    STYLE_CHECKBOX_DEFAULT = ttk.Style()
    STYLE_CHECKBOX_DEFAULT.configure("TCheckbutton", background=VAR.GUI_COLOR_PRIMARY)

    STYLE_CHECKBOX_PRIMARY = ttk.Style()
    STYLE_CHECKBOX_PRIMARY.configure(VAR.CHECKBOX_STYLE_PRIMARY, background=VAR.GUI_COLOR_PRIMARY)

    STYLE_CHECKBOX_SECUNDARY = ttk.Style()
    STYLE_CHECKBOX_SECUNDARY.configure(VAR.CHECKBOX_STYLE_SECUNDARY, background=VAR.GUI_COLOR_SECONDARY)
